# ----------------------------
# Makefile Options
# ----------------------------

NAME = BTF
ICON = icon.png
DESCRIPTION = "Binary to Float"
COMPRESSED = NO

CFLAGS = -Wall -Wextra -Oz
CXXFLAGS = -Wall -Wextra -Oz

# ----------------------------

include $(shell cedev-config --makefile)
