# ----------------------------
# Makefile Options
# ----------------------------

NAME = BTI
ICON = icon.png
DESCRIPTION = "Binary to Instruction"
COMPRESSED = NO

CFLAGS = -Wall -Wextra -Oz
CXXFLAGS = -Wall -Wextra -Oz

# ----------------------------

include $(shell cedev-config --makefile)
