# ----------------------------
# Makefile Options
# ----------------------------

NAME = TAB
ICON = icon.png
DESCRIPTION = "Try All Bases"
COMPRESSED = NO

CFLAGS = -Wall -Wextra -Oz
CXXFLAGS = -Wall -Wextra -Oz

# ----------------------------

include $(shell cedev-config --makefile)
