# ----------------------------
# Makefile Options
# ----------------------------

NAME = FTB
ICON = icon.png
DESCRIPTION = "Float to Binary"
COMPRESSED = NO

CFLAGS = -Wall -Wextra -Oz
CXXFLAGS = -Wall -Wextra -Oz

# ----------------------------

include $(shell cedev-config --makefile)
