# ----------------------------
# Makefile Options
# ----------------------------

NAME = KMAP 
ICON = icon.png
DESCRIPTION = "KMap"
COMPRESSED = NO

CFLAGS = -Wall -Wextra -Oz
CXXFLAGS = -Wall -Wextra -Oz

# ----------------------------

include $(shell cedev-config --makefile)
